function __global_object_depths() {
	// Initialise the global array that allows the lookup of the depth of a given object
	// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
	// NOTE: MacroExpansion is used to insert the array initialisation at import time
	gml_pragma( "global", "__global_object_depths()");

	// insert the generated arrays here
	global.__objectDepths[0] = 0; // objObject
	global.__objectDepths[1] = 0; // objEntity
	global.__objectDepths[2] = 0; // objEnemy
	global.__objectDepths[3] = 0; // objProjectile
	global.__objectDepths[4] = 0; // parent_Destruible
	global.__objectDepths[5] = 0; // parent_Enemigo
	global.__objectDepths[6] = 0; // parent_Jefe
	global.__objectDepths[7] = 0; // parent_Jugador
	global.__objectDepths[8] = 0; // parent_Pickup
	global.__objectDepths[9] = 0; // parent_Solid
	global.__objectDepths[10] = 0; // parent_Bullet
	global.__objectDepths[11] = 0; // obj_Seguido_Por_Camara
	global.__objectDepths[12] = 0; // sala_Heal_Control
	global.__objectDepths[13] = 0; // sala_Eleccion_Control
	global.__objectDepths[14] = -1000; // control_Ambiental
	global.__objectDepths[15] = 0; // control_Anuncios
	global.__objectDepths[16] = 0; // control_Arcade
	global.__objectDepths[17] = 0; // control_Audio
	global.__objectDepths[18] = 0; // control_Camera
	global.__objectDepths[19] = 0; // control_Debugger
	global.__objectDepths[20] = -2000; // control_Dungeon
	global.__objectDepths[21] = 99; // control_floorDetails
	global.__objectDepths[22] = 0; // control_Gamepad
	global.__objectDepths[23] = -1000; // control_News
	global.__objectDepths[24] = 0; // control_Room
	global.__objectDepths[25] = 0; // control_Tiles
	global.__objectDepths[26] = -2001; // control_UI
	global.__objectDepths[27] = -999999; // objItemViewer
	global.__objectDepths[28] = 0; // control_Multi_Camara
	global.__objectDepths[29] = -2000; // controlador_Movimiento
	global.__objectDepths[30] = -2000; // controlador_Disparo
	global.__objectDepths[31] = 0; // obj_Jugador
	global.__objectDepths[32] = 0; // obj_LocalPlayer
	global.__objectDepths[33] = 0; // objPet
	global.__objectDepths[34] = 190; // obj_Jugador_Chaos_Zone
	global.__objectDepths[35] = 60; // obj_Jugador_Totem_Vortex
	global.__objectDepths[36] = 0; // objPlayerClone
	global.__objectDepths[37] = 0; // obj_LittleMe
	global.__objectDepths[38] = 1; // obj_Jugador_Disparo
	global.__objectDepths[39] = 1; // obj_Jugador_Disparo_Fuego
	global.__objectDepths[40] = -120; // obj_Jugador_Disparo_Laser
	global.__objectDepths[41] = -120; // obj_Jugador_Disparo_Finger
	global.__objectDepths[42] = -120; // obj_Jugador_Disparo_Scythe
	global.__objectDepths[43] = -150; // obj_Jugador_Disparo_Estatico
	global.__objectDepths[44] = 0; // obj_Jugador_Rocket
	global.__objectDepths[45] = -500; // objFleshSoul
	global.__objectDepths[46] = 0; // obj_Dummy
	global.__objectDepths[47] = 0; // objToxicArea
	global.__objectDepths[48] = 0; // objCthulhuAura
	global.__objectDepths[49] = 0; // parent_Jugador_Friend
	global.__objectDepths[50] = -60; // obj_Jugador_Friend_Mini_Cthulhu
	global.__objectDepths[51] = -60; // obj_Jugador_Friend_Blue_Cthulhu
	global.__objectDepths[52] = -60; // obj_Jugador_Friend_Green_Cthulhu
	global.__objectDepths[53] = -60; // obj_Jugador_Friend_Yellow_Cthulhu
	global.__objectDepths[54] = -60; // obj_Jugador_Friend_Gold_Cthulhu
	global.__objectDepths[55] = 0; // obj_Jefe_KingSlime
	global.__objectDepths[56] = 0; // obj_Jefe_SuperSlime
	global.__objectDepths[57] = 0; // obj_Jefe_YellowSlime
	global.__objectDepths[58] = 0; // obj_Jefe_BlackSlime
	global.__objectDepths[59] = 0; // obj_Jefe_GreenSlime
	global.__objectDepths[60] = 0; // obj_Jefe_RedSlime
	global.__objectDepths[61] = 0; // obj_Jefe_PurpleSlime
	global.__objectDepths[62] = 0; // obj_Jefe_RealBlackSlime
	global.__objectDepths[63] = 0; // obj_Jefe_OrangeSlime
	global.__objectDepths[64] = 0; // obj_Jefe_WhiteSlime
	global.__objectDepths[65] = 0; // obj_Jefe_GlowSlime
	global.__objectDepths[66] = 0; // obj_Jefe_AquaSlime
	global.__objectDepths[67] = 0; // obj_Jefe_ShadowSlime
	global.__objectDepths[68] = 0; // objJefeGreenGigadusa
	global.__objectDepths[69] = 0; // objJefeGreatPapasa
	global.__objectDepths[70] = 0; // objJefeGigadusa
	global.__objectDepths[71] = 0; // objJefeCreep
	global.__objectDepths[72] = 0; // objJefeMadSlime
	global.__objectDepths[73] = 0; // obj_Jefe_KingSlimeFinal
	global.__objectDepths[74] = 0; // obj_Jefe_DarkSlimeking
	global.__objectDepths[75] = 0; // obj_Jefe_GhostKingSlime
	global.__objectDepths[76] = 0; // objJefeLodeslime
	global.__objectDepths[77] = 0; // objJefeBombslime
	global.__objectDepths[78] = 0; // objJefeGangslime
	global.__objectDepths[79] = 0; // objJefeRockslime
	global.__objectDepths[80] = 0; // objJefePlanetslime
	global.__objectDepths[81] = 0; // objJefeBoneslime
	global.__objectDepths[82] = 0; // objJefeBulbslime
	global.__objectDepths[83] = 0; // objJefeBigsnake
	global.__objectDepths[84] = 0; // objJefeEaterslime
	global.__objectDepths[85] = -100; // obj_Jefe_Fuego
	global.__objectDepths[86] = 0; // objGiantSlimeBall
	global.__objectDepths[87] = 0; // objJefeBulbPointer
	global.__objectDepths[88] = 99; // objJefeBulbslimeLazer
	global.__objectDepths[89] = -802; // objJefePlanetSlimeMoon
	global.__objectDepths[90] = 600; // obj_Jefe_AquaSlime_Aura
	global.__objectDepths[91] = 0; // objJefeGangslimeShoot
	global.__objectDepths[92] = 0; // objJefeBigsnakePart
	global.__objectDepths[93] = -150; // obj_ChainSlimeChainBall
	global.__objectDepths[94] = -100; // obj_TomahawkSkull
	global.__objectDepths[95] = -700; // obj_MageSkeleton_Fireball
	global.__objectDepths[96] = -700; // objFallingRock
	global.__objectDepths[97] = -120; // obj_Enemy_Laser
	global.__objectDepths[98] = 0; // obj_Enemy_ClockStop
	global.__objectDepths[99] = 0; // obj_Skeleton
	global.__objectDepths[100] = 0; // obj_ChallengeSlime
	global.__objectDepths[101] = 0; // obj_Slime
	global.__objectDepths[102] = 0; // obj_ActionSlime
	global.__objectDepths[103] = 0; // obj_ChainSlime
	global.__objectDepths[104] = 0; // obj_Tomahawk
	global.__objectDepths[105] = 0; // obj_Hardmahawk
	global.__objectDepths[106] = 0; // obj_Snake
	global.__objectDepths[107] = 0; // obj_MageSkeleton
	global.__objectDepths[108] = 0; // obj_Summoner
	global.__objectDepths[109] = 0; // obj_StompSlime
	global.__objectDepths[110] = 0; // obj_Conejo
	global.__objectDepths[111] = 0; // obj_Bat
	global.__objectDepths[112] = 0; // obj_Bouncer
	global.__objectDepths[113] = 0; // obj_Mitosis
	global.__objectDepths[114] = 0; // obj_Shadow_Spawn
	global.__objectDepths[115] = 0; // obj_Mimic
	global.__objectDepths[116] = 0; // objSun
	global.__objectDepths[117] = 0; // objCofreMini
	global.__objectDepths[118] = 0; // objCofreMiniBlue
	global.__objectDepths[119] = 0; // objCofreMiniGold
	global.__objectDepths[120] = 0; // objCofreMiniExperience
	global.__objectDepths[121] = 0; // objCofreMiniKeys
	global.__objectDepths[122] = 0; // objCofreMiniBombs
	global.__objectDepths[123] = 0; // objCofreBossKey
	global.__objectDepths[124] = 0; // obj_Cofre_Tienda
	global.__objectDepths[125] = 0; // obj_Cofre_Health
	global.__objectDepths[126] = 0; // obj_Cofre_Level
	global.__objectDepths[127] = 0; // obj_Cofre_Arcade
	global.__objectDepths[128] = 0; // obj_Boss_Chest
	global.__objectDepths[129] = 0; // obj_Cofre_Eleccion
	global.__objectDepths[130] = 0; // obj_Cofre_Mimic
	global.__objectDepths[131] = 0; // obj_Cofre_ExpMimic
	global.__objectDepths[132] = 0; // obj_Cofre_KeyMimic
	global.__objectDepths[133] = 0; // obj_Cofre_SellMimic
	global.__objectDepths[134] = 0; // obj_Cofre_Tesoro
	global.__objectDepths[135] = 0; // obj_Cofre_Tesoro_Random
	global.__objectDepths[136] = 0; // obj_Ultimo_Yo
	global.__objectDepths[137] = -3; // obj_Block
	global.__objectDepths[138] = -3; // object358
	global.__objectDepths[139] = 0; // obj_Decoracion
	global.__objectDepths[140] = 0; // obj_Enemigo_Spawner
	global.__objectDepths[141] = 0; // obj_Agua
	global.__objectDepths[142] = 0; // obj_Void
	global.__objectDepths[143] = 1000; // obj_Suelo
	global.__objectDepths[144] = 500; // obj_Techo
	global.__objectDepths[145] = 200; // obj_Muro
	global.__objectDepths[146] = 100; // obj_Esquina
	global.__objectDepths[147] = 10; // obj_Puerta
	global.__objectDepths[148] = 10; // obj_Puerta_Subterraneo
	global.__objectDepths[149] = 0; // obj_Escaleras
	global.__objectDepths[150] = 999; // obj_Hielo
	global.__objectDepths[151] = 0; // obj_Bloqueador
	global.__objectDepths[152] = 0; // obj_Rocas
	global.__objectDepths[153] = 0; // obj_Skeletons
	global.__objectDepths[154] = 100; // obj_Vasija
	global.__objectDepths[155] = 0; // obj_Antorcha
	global.__objectDepths[156] = 0; // obj_Pinchos
	global.__objectDepths[157] = 0; // objSpikeBlock
	global.__objectDepths[158] = 0; // obj_Bloqueador_Activado_Rojo
	global.__objectDepths[159] = 0; // obj_Bloqueador_Activado_Azul
	global.__objectDepths[160] = 0; // obj_Pinchos_Suelo
	global.__objectDepths[161] = 0; // obj_Bloqueador_Laser
	global.__objectDepths[162] = 0; // objSkullFlame
	global.__objectDepths[163] = 0; // obj_Rebotador
	global.__objectDepths[164] = 0; // obj_Atractor
	global.__objectDepths[165] = 0; // objBuildChanger
	global.__objectDepths[166] = 0; // objPiggyBank
	global.__objectDepths[167] = 0; // obj_Armario
	global.__objectDepths[168] = 0; // obj_Moneda
	global.__objectDepths[169] = 0; // obj_Key
	global.__objectDepths[170] = 0; // obj_BossKey
	global.__objectDepths[171] = 0; // obj_PickupBomb
	global.__objectDepths[172] = 0; // obj_Salud
	global.__objectDepths[173] = 0; // obj_HalfHeart
	global.__objectDepths[174] = 0; // obj_ShieldHeart
	global.__objectDepths[175] = 0; // obj_TimeHeart
	global.__objectDepths[176] = 0; // obj_SkullHeart
	global.__objectDepths[177] = 0; // obj_GoldHeart
	global.__objectDepths[178] = 0; // obj_BatteryHeart
	global.__objectDepths[179] = -800; // objExperienceOrb
	global.__objectDepths[180] = 0; // objSlimekingCrown
	global.__objectDepths[181] = 0; // objSlimekingMoustache
	global.__objectDepths[182] = 0; // objBosskeySpawner
	global.__objectDepths[183] = 0; // objBomb
	global.__objectDepths[184] = 0; // objBombExplosion
	global.__objectDepths[185] = 0; // transicion_Jefe
	global.__objectDepths[186] = 0; // transicion_Jugador
	global.__objectDepths[187] = -1; // transicion_Letras
	global.__objectDepths[188] = 0; // transicion_Control
	global.__objectDepths[189] = -99999; // control
	global.__objectDepths[190] = -10; // floorLighting
	global.__objectDepths[191] = -2; // obj_Light_Environment
	global.__objectDepths[192] = -80; // obj_Light_Dynamic
	global.__objectDepths[193] = -3; // obj_Block_Caster
	global.__objectDepths[194] = 0; // fx_Sprite_Alpha
	global.__objectDepths[195] = 0; // fx_Sprite
	global.__objectDepths[196] = 200; // fx_Sprite_Persistent
	global.__objectDepths[197] = 1; // fx_Flames
	global.__objectDepths[198] = -1000; // fx_Transition_In
	global.__objectDepths[199] = -1500; // fx_Transition_In_White
	global.__objectDepths[200] = -1001; // fx_Transition_Out
	global.__objectDepths[201] = -99999; // fx_Transition_Unlock
	global.__objectDepths[202] = -1000; // fx_Transition_Out_Full
	global.__objectDepths[203] = -999999; // objCharacterUnlock
	global.__objectDepths[204] = -1000; // fx_Transition_OutSlow
	global.__objectDepths[205] = -1000; // fx_Game_End
	global.__objectDepths[206] = -9999999; // fx_Sprite_Grow
	global.__objectDepths[207] = -1000; // fx_Transition_Room
	global.__objectDepths[208] = -600; // fxLazer
	global.__objectDepths[209] = -10; // fxTransition2
	global.__objectDepths[210] = -10; // fxTransition3
	global.__objectDepths[211] = -2002; // fx_Letras_Mapa
	global.__objectDepths[212] = -999999; // fxRoomFlash
	global.__objectDepths[213] = 0; // fx_Autoguardado
	global.__objectDepths[214] = 0; // fx_FloatingText
	global.__objectDepths[215] = -50; // fx_Laser_Particle
	global.__objectDepths[216] = 180; // objGuts
	global.__objectDepths[217] = 180; // objFloorDetail
	global.__objectDepths[218] = -1000; // test_video
	global.__objectDepths[219] = 0; // obj_Logo
	global.__objectDepths[220] = 0; // control_Intro_ModoTorre
	global.__objectDepths[221] = 0; // obj_Menu_Icon_ModoEndless
	global.__objectDepths[222] = 0; // obj_Menu_Icon_ModoArcade
	global.__objectDepths[223] = 0; // obj_Menu_Icon_Editor
	global.__objectDepths[224] = -1000; // obj_Menu_Icon_Objetos
	global.__objectDepths[225] = 0; // obj_Menu_Icon_Salir
	global.__objectDepths[226] = 0; // obj_Menu_Icon_Logros
	global.__objectDepths[227] = -1000; // obj_Menu_Icon_Moneda
	global.__objectDepths[228] = 0; // obj_Menu_Icon_Ranking
	global.__objectDepths[229] = -1000; // obj_Menu_Icon_ModoTorre
	global.__objectDepths[230] = 10; // obj_Menu_Icon_Slime
	global.__objectDepths[231] = 10; // obj_Menu_Icon_Arcade
	global.__objectDepths[232] = -1000; // obj_Menu_Icon_Time
	global.__objectDepths[233] = -1000; // obj_Menu_Icon_Map
	global.__objectDepths[234] = -997; // control_Primera
	global.__objectDepths[235] = 0; // control_Menu
	global.__objectDepths[236] = -998; // obj_Perfil
	global.__objectDepths[237] = 1; // obj_Menu_ModoTorre
	global.__objectDepths[238] = 0; // obj_Menu_Modos
	global.__objectDepths[239] = 0; // obj_Menu_Ranking
	global.__objectDepths[240] = 0; // obj_Menu_Biblioteca
	global.__objectDepths[241] = 0; // obj_Menu_Opciones
	global.__objectDepths[242] = 0; // obj_Menu_Volver_Menu
	global.__objectDepths[243] = 1; // obj_Menu_Exit
	global.__objectDepths[244] = -250; // obj_UI_Monedas
	global.__objectDepths[245] = 0; // obj_Menu_Promo_Code
	global.__objectDepths[246] = -2002; // obj_Boton_Opciones_Ingame_Reiniciar
	global.__objectDepths[247] = 1000; // fx_Sprite_KingSlime
	global.__objectDepths[248] = -50; // control_GameOver
	global.__objectDepths[249] = 0; // obj_Menu_MenuPrincipal
	global.__objectDepths[250] = 0; // obj_Menu_JugarDeNuevo
	global.__objectDepths[251] = 0; // obj_Menu_EnviarPuntuacion
	global.__objectDepths[252] = -39; // obj_Menu_GameOver_Play
	global.__objectDepths[253] = -10; // obj_Nuevo_Menu_GameOver_Play
	global.__objectDepths[254] = 0; // control_Opciones
	global.__objectDepths[255] = 0; // obj_Menu_TipoCamara
	global.__objectDepths[256] = 0; // obj_Menu_TipoControl
	global.__objectDepths[257] = 0; // obj_Menu_TipoSonido
	global.__objectDepths[258] = 0; // obj_Opciones_Volver
	global.__objectDepths[259] = -50; // control_Ranking
	global.__objectDepths[260] = -50; // obj_Menu_Boton_Volver
	global.__objectDepths[261] = -50; // obj_Menu_Boton_Tiempo
	global.__objectDepths[262] = -50; // obj_Menu_Boton_Modo
	global.__objectDepths[263] = -50; // obj_Menu_Boton_Tower
	global.__objectDepths[264] = -50; // obj_Menu_Boton_Dificultad
	global.__objectDepths[265] = -10; // obj_Menu_Nuevo_Boton_Tiempo
	global.__objectDepths[266] = -10; // obj_Menu_Nuevo_Boton_Dificultad
	global.__objectDepths[267] = -10; // obj_Menu_Nuevo_Modo
	global.__objectDepths[268] = -10; // obj_Menu_Nuevo_Boton_Tower
	global.__objectDepths[269] = -150; // control_Biblioteca
	global.__objectDepths[270] = -50; // obj_Biblioteca_Item
	global.__objectDepths[271] = -50; // obj_Biblioteca_Comprar
	global.__objectDepths[272] = -50; // obj_Biblioteca_Desbloqueados
	global.__objectDepths[273] = -49; // obj_Biblioteca_Pagina
	global.__objectDepths[274] = -50; // obj_Biblioteca_Pagina_Icon
	global.__objectDepths[275] = -10; // obj_Biblioteca_Nuevo_Pagina
	global.__objectDepths[276] = -10; // obj_Biblioteca_Nuevo_Buy
	global.__objectDepths[277] = 0; // obj_Menu_ModoTorre_Play
	global.__objectDepths[278] = 0; // obj_Menu_Modo_Endless
	global.__objectDepths[279] = 0; // obj_Menu_Modo_Arcade
	global.__objectDepths[280] = 0; // obj_Menu_Continuar
	global.__objectDepths[281] = 0; // obj_Menu_Continuar_Endless
	global.__objectDepths[282] = 0; // obj_Menu_Continuar_Arcade
	global.__objectDepths[283] = -800; // obj_Menu_Modo_Dificultad
	global.__objectDepths[284] = -13; // obj_Menu_Nuevo_Controller
	global.__objectDepths[285] = 0; // parent_Menu_Nuevo
	global.__objectDepths[286] = -9; // obj_Menu_Nuevo_Logo
	global.__objectDepths[287] = -10; // obj_Menu_Nuevo_Stats
	global.__objectDepths[288] = -9; // obj_Menu_Nuevo_Black
	global.__objectDepths[289] = -10; // obj_Menu_Nuevo_Play
	global.__objectDepths[290] = -10; // obj_Menu_Nuevo_Challenges
	global.__objectDepths[291] = -10; // obj_Menu_Nuevo_Ranking
	global.__objectDepths[292] = -10; // obj_Menu_Nuevo_Opciones
	global.__objectDepths[293] = -10; // obj_Menu_Nuevo_Items
	global.__objectDepths[294] = -10; // obj_Menu_Nuevo_Pets
	global.__objectDepths[295] = -10; // obj_Menu_Nuevo_Exit
	global.__objectDepths[296] = -10; // obj_Menu_Nuevo_Back
	global.__objectDepths[297] = -10; // obj_Menu_Nuevo_CharacterSelect
	global.__objectDepths[298] = -10; // obj_Menu_Nuevo_Codigo
	global.__objectDepths[299] = -10; // obj_Menu_Nuevo_Adventure_Mode
	global.__objectDepths[300] = -10; // obj_Menu_Nuevo_Endless_Mode
	global.__objectDepths[301] = -10; // obj_Menu_Nuevo_Endless_Mode_Play
	global.__objectDepths[302] = -10; // obj_Menu_Nuevo_DailyRun_Mode
	global.__objectDepths[303] = -10; // obj_Menu_Nuevo_DailyRun_Mode_Play
	global.__objectDepths[304] = -1000; // obj_Menu_Nuevo_Endless_Info
	global.__objectDepths[305] = -1000; // obj_Menu_Nuevo_DailyRun_Info
	global.__objectDepths[306] = -10; // obj_Menu_Nuevo_Arcade_Mode
	global.__objectDepths[307] = -10; // obj_Menu_Nuevo_Audio
	global.__objectDepths[308] = -10; // obj_Menu_Nuevo_Autosave
	global.__objectDepths[309] = -10; // obj_Menu_Nuevo_Continuar
	global.__objectDepths[310] = -10; // obj_Menu_Nuevo_Quality
	global.__objectDepths[311] = -10; // obj_Menu_Nuevo_Dificultad
	global.__objectDepths[312] = -10; // obj_Menu_Nuevo_Seed
	global.__objectDepths[313] = -10; // obj_Menu_Nuevo_Freebies
	global.__objectDepths[314] = -10; // obj_Menu_Nuevo_ControllerMap
	global.__objectDepths[315] = -10; // obj_Menu_Nuevo_DefaultControllerMap
	global.__objectDepths[316] = 0; // obj_Menu_Nuevo_Fake_Objetivo
	global.__objectDepths[317] = -150; // control_Pets
	global.__objectDepths[318] = -50; // obj_Pets_Comprar
	global.__objectDepths[319] = -13; // selectionController
	global.__objectDepths[320] = -12; // objCharacterInfo
	global.__objectDepths[321] = -11; // objCharacterSelect
	global.__objectDepths[322] = -10; // objCharacterSelectPrevious
	global.__objectDepths[323] = -10; // objCharacterSelectNext
	global.__objectDepths[324] = -13; // challengeSelectionController
	global.__objectDepths[325] = -12; // objChallengeInfo
	global.__objectDepths[326] = -11; // objChallengeSelect
	global.__objectDepths[327] = -2002; // obj_UI_Map
	global.__objectDepths[328] = -500; // objCutsceneGeneral
	global.__objectDepths[329] = -150; // objCutsceneIntro
	global.__objectDepths[330] = -150; // objCutsceneTransition
	global.__objectDepths[331] = -100; // objCutscene01Controller
	global.__objectDepths[332] = -15; // sprCutscene01Muzzy
	global.__objectDepths[333] = 20; // objCutscene01House
	global.__objectDepths[334] = 50; // objCutscene01Moon
	global.__objectDepths[335] = 32; // objCutscene01Mountains
	global.__objectDepths[336] = 120; // objCutscene01Night
	global.__objectDepths[337] = 30; // objCutscene01Background
	global.__objectDepths[338] = -20; // objCutscene01Slimeking
	global.__objectDepths[339] = -50; // objCutscene01SlimekingLaugh
	global.__objectDepths[340] = 0; // objCutscene01SmokeSpawner
	global.__objectDepths[341] = -10; // objCutscene01Tower
	global.__objectDepths[342] = -20; // objCutscene01Player
	global.__objectDepths[343] = 31; // objCutscene01Woods
	global.__objectDepths[344] = -20; // objCutscene01Smoke
	global.__objectDepths[345] = -11; // objCutscene01SmallRock
	global.__objectDepths[346] = 20; // objCutscene01MountainsF
	global.__objectDepths[347] = -20; // objCutscene01Slimeking2
	global.__objectDepths[348] = -11; // objCutscene01Hair
	global.__objectDepths[349] = -10; // objCutscene01Foreground
	global.__objectDepths[350] = -5; // objCutscene01Dust
	global.__objectDepths[351] = -100; // objCutscene02Controller
	global.__objectDepths[352] = 10; // objCutscene02Overlay
	global.__objectDepths[353] = -20; // objCutscene02SlimekingBig
	global.__objectDepths[354] = -11; // objCutscene02Particles
	global.__objectDepths[355] = -100; // objCutscene03Controller
	global.__objectDepths[356] = 40; // objCutscene03Background
	global.__objectDepths[357] = 30; // objCutscene03Bar
	global.__objectDepths[358] = 20; // objCutscene03Bartender
	global.__objectDepths[359] = -10; // objCutscene03Door
	global.__objectDepths[360] = -150; // objCutscene03Flash
	global.__objectDepths[361] = -70; // objCutscene03Table
	global.__objectDepths[362] = -70; // objCutscene03People
	global.__objectDepths[363] = -20; // objCutscene03Slimeking
	global.__objectDepths[364] = -25; // objCutscene03SlimekingMoustache
	global.__objectDepths[365] = 0; // objCutscene03WindowGlow
	global.__objectDepths[366] = -99; // objCutscene03Overlay
	global.__objectDepths[367] = -81; // objCutscene03Cry
	global.__objectDepths[368] = -70; // objCutscene04Character
	global.__objectDepths[369] = 0; // objCutscene04Background
	global.__objectDepths[370] = -90; // objCutscene04LightCircle
	global.__objectDepths[371] = -60; // objCutscene04Dust
	global.__objectDepths[372] = 0; // objCutscene04FireParticleSpawner
	global.__objectDepths[373] = -80; // objCutscene04FireParticle
	global.__objectDepths[374] = -100; // objCutscene04Controller
	global.__objectDepths[375] = -100; // objCutscene05Controller
	global.__objectDepths[376] = 100; // objCutscene05BG
	global.__objectDepths[377] = -1; // objCutscene05Player
	global.__objectDepths[378] = 0; // objCutscene05Crown
	global.__objectDepths[379] = 0; // objCutscene05Slimeking
	global.__objectDepths[380] = 80; // objCutscene05Stairs
	global.__objectDepths[381] = -100; // objCutscene06Controller
	global.__objectDepths[382] = 100; // objCutscene06BG
	global.__objectDepths[383] = 60; // objCutscene06Portal
	global.__objectDepths[384] = -100; // objCutscene07Controller
	global.__objectDepths[385] = 100; // objCutscene07BG
	global.__objectDepths[386] = 10; // objCutscene07Throne
	global.__objectDepths[387] = 0; // objCutscene07Player
	global.__objectDepths[388] = 0; // objCutscene07Congratulations
	global.__objectDepths[389] = -800; // objItemInfo
	global.__objectDepths[390] = 0; // control_GamepadMapping
	global.__objectDepths[391] = 0; // control_Steam
	global.__objectDepths[392] = 0; // gamepad_MenuNav


	global.__objectNames[0] = "objObject";
	global.__objectNames[1] = "objEntity";
	global.__objectNames[2] = "objEnemy";
	global.__objectNames[3] = "objProjectile";
	global.__objectNames[4] = "parent_Destruible";
	global.__objectNames[5] = "parent_Enemigo";
	global.__objectNames[6] = "parent_Jefe";
	global.__objectNames[7] = "parent_Jugador";
	global.__objectNames[8] = "parent_Pickup";
	global.__objectNames[9] = "parent_Solid";
	global.__objectNames[10] = "parent_Bullet";
	global.__objectNames[11] = "obj_Seguido_Por_Camara";
	global.__objectNames[12] = "sala_Heal_Control";
	global.__objectNames[13] = "sala_Eleccion_Control";
	global.__objectNames[14] = "control_Ambiental";
	global.__objectNames[15] = "control_Anuncios";
	global.__objectNames[16] = "control_Arcade";
	global.__objectNames[17] = "control_Audio";
	global.__objectNames[18] = "control_Camera";
	global.__objectNames[19] = "control_Debugger";
	global.__objectNames[20] = "control_Dungeon";
	global.__objectNames[21] = "control_floorDetails";
	global.__objectNames[22] = "control_Gamepad";
	global.__objectNames[23] = "control_News";
	global.__objectNames[24] = "control_Room";
	global.__objectNames[25] = "control_Tiles";
	global.__objectNames[26] = "control_UI";
	global.__objectNames[27] = "objItemViewer";
	global.__objectNames[28] = "control_Multi_Camara";
	global.__objectNames[29] = "controlador_Movimiento";
	global.__objectNames[30] = "controlador_Disparo";
	global.__objectNames[31] = "obj_Jugador";
	global.__objectNames[32] = "obj_LocalPlayer";
	global.__objectNames[33] = "objPet";
	global.__objectNames[34] = "obj_Jugador_Chaos_Zone";
	global.__objectNames[35] = "obj_Jugador_Totem_Vortex";
	global.__objectNames[36] = "objPlayerClone";
	global.__objectNames[37] = "obj_LittleMe";
	global.__objectNames[38] = "obj_Jugador_Disparo";
	global.__objectNames[39] = "obj_Jugador_Disparo_Fuego";
	global.__objectNames[40] = "obj_Jugador_Disparo_Laser";
	global.__objectNames[41] = "obj_Jugador_Disparo_Finger";
	global.__objectNames[42] = "obj_Jugador_Disparo_Scythe";
	global.__objectNames[43] = "obj_Jugador_Disparo_Estatico";
	global.__objectNames[44] = "obj_Jugador_Rocket";
	global.__objectNames[45] = "objFleshSoul";
	global.__objectNames[46] = "obj_Dummy";
	global.__objectNames[47] = "objToxicArea";
	global.__objectNames[48] = "objCthulhuAura";
	global.__objectNames[49] = "parent_Jugador_Friend";
	global.__objectNames[50] = "obj_Jugador_Friend_Mini_Cthulhu";
	global.__objectNames[51] = "obj_Jugador_Friend_Blue_Cthulhu";
	global.__objectNames[52] = "obj_Jugador_Friend_Green_Cthulhu";
	global.__objectNames[53] = "obj_Jugador_Friend_Yellow_Cthulhu";
	global.__objectNames[54] = "obj_Jugador_Friend_Gold_Cthulhu";
	global.__objectNames[55] = "obj_Jefe_KingSlime";
	global.__objectNames[56] = "obj_Jefe_SuperSlime";
	global.__objectNames[57] = "obj_Jefe_YellowSlime";
	global.__objectNames[58] = "obj_Jefe_BlackSlime";
	global.__objectNames[59] = "obj_Jefe_GreenSlime";
	global.__objectNames[60] = "obj_Jefe_RedSlime";
	global.__objectNames[61] = "obj_Jefe_PurpleSlime";
	global.__objectNames[62] = "obj_Jefe_RealBlackSlime";
	global.__objectNames[63] = "obj_Jefe_OrangeSlime";
	global.__objectNames[64] = "obj_Jefe_WhiteSlime";
	global.__objectNames[65] = "obj_Jefe_GlowSlime";
	global.__objectNames[66] = "obj_Jefe_AquaSlime";
	global.__objectNames[67] = "obj_Jefe_ShadowSlime";
	global.__objectNames[68] = "objJefeGreenGigadusa";
	global.__objectNames[69] = "objJefeGreatPapasa";
	global.__objectNames[70] = "objJefeGigadusa";
	global.__objectNames[71] = "objJefeCreep";
	global.__objectNames[72] = "objJefeMadSlime";
	global.__objectNames[73] = "obj_Jefe_KingSlimeFinal";
	global.__objectNames[74] = "obj_Jefe_DarkSlimeking";
	global.__objectNames[75] = "obj_Jefe_GhostKingSlime";
	global.__objectNames[76] = "objJefeLodeslime";
	global.__objectNames[77] = "objJefeBombslime";
	global.__objectNames[78] = "objJefeGangslime";
	global.__objectNames[79] = "objJefeRockslime";
	global.__objectNames[80] = "objJefePlanetslime";
	global.__objectNames[81] = "objJefeBoneslime";
	global.__objectNames[82] = "objJefeBulbslime";
	global.__objectNames[83] = "objJefeBigsnake";
	global.__objectNames[84] = "objJefeEaterslime";
	global.__objectNames[85] = "obj_Jefe_Fuego";
	global.__objectNames[86] = "objGiantSlimeBall";
	global.__objectNames[87] = "objJefeBulbPointer";
	global.__objectNames[88] = "objJefeBulbslimeLazer";
	global.__objectNames[89] = "objJefePlanetSlimeMoon";
	global.__objectNames[90] = "obj_Jefe_AquaSlime_Aura";
	global.__objectNames[91] = "objJefeGangslimeShoot";
	global.__objectNames[92] = "objJefeBigsnakePart";
	global.__objectNames[93] = "obj_ChainSlimeChainBall";
	global.__objectNames[94] = "obj_TomahawkSkull";
	global.__objectNames[95] = "obj_MageSkeleton_Fireball";
	global.__objectNames[96] = "objFallingRock";
	global.__objectNames[97] = "obj_Enemy_Laser";
	global.__objectNames[98] = "obj_Enemy_ClockStop";
	global.__objectNames[99] = "obj_Skeleton";
	global.__objectNames[100] = "obj_ChallengeSlime";
	global.__objectNames[101] = "obj_Slime";
	global.__objectNames[102] = "obj_ActionSlime";
	global.__objectNames[103] = "obj_ChainSlime";
	global.__objectNames[104] = "obj_Tomahawk";
	global.__objectNames[105] = "obj_Hardmahawk";
	global.__objectNames[106] = "obj_Snake";
	global.__objectNames[107] = "obj_MageSkeleton";
	global.__objectNames[108] = "obj_Summoner";
	global.__objectNames[109] = "obj_StompSlime";
	global.__objectNames[110] = "obj_Conejo";
	global.__objectNames[111] = "obj_Bat";
	global.__objectNames[112] = "obj_Bouncer";
	global.__objectNames[113] = "obj_Mitosis";
	global.__objectNames[114] = "obj_Shadow_Spawn";
	global.__objectNames[115] = "obj_Mimic";
	global.__objectNames[116] = "objSun";
	global.__objectNames[117] = "objCofreMini";
	global.__objectNames[118] = "objCofreMiniBlue";
	global.__objectNames[119] = "objCofreMiniGold";
	global.__objectNames[120] = "objCofreMiniExperience";
	global.__objectNames[121] = "objCofreMiniKeys";
	global.__objectNames[122] = "objCofreMiniBombs";
	global.__objectNames[123] = "objCofreBossKey";
	global.__objectNames[124] = "obj_Cofre_Tienda";
	global.__objectNames[125] = "obj_Cofre_Health";
	global.__objectNames[126] = "obj_Cofre_Level";
	global.__objectNames[127] = "obj_Cofre_Arcade";
	global.__objectNames[128] = "obj_Boss_Chest";
	global.__objectNames[129] = "obj_Cofre_Eleccion";
	global.__objectNames[130] = "obj_Cofre_Mimic";
	global.__objectNames[131] = "obj_Cofre_ExpMimic";
	global.__objectNames[132] = "obj_Cofre_KeyMimic";
	global.__objectNames[133] = "obj_Cofre_SellMimic";
	global.__objectNames[134] = "obj_Cofre_Tesoro";
	global.__objectNames[135] = "obj_Cofre_Tesoro_Random";
	global.__objectNames[136] = "obj_Ultimo_Yo";
	global.__objectNames[137] = "obj_Block";
	global.__objectNames[138] = "object358";
	global.__objectNames[139] = "obj_Decoracion";
	global.__objectNames[140] = "obj_Enemigo_Spawner";
	global.__objectNames[141] = "obj_Agua";
	global.__objectNames[142] = "obj_Void";
	global.__objectNames[143] = "obj_Suelo";
	global.__objectNames[144] = "obj_Techo";
	global.__objectNames[145] = "obj_Muro";
	global.__objectNames[146] = "obj_Esquina";
	global.__objectNames[147] = "obj_Puerta";
	global.__objectNames[148] = "obj_Puerta_Subterraneo";
	global.__objectNames[149] = "obj_Escaleras";
	global.__objectNames[150] = "obj_Hielo";
	global.__objectNames[151] = "obj_Bloqueador";
	global.__objectNames[152] = "obj_Rocas";
	global.__objectNames[153] = "obj_Skeletons";
	global.__objectNames[154] = "obj_Vasija";
	global.__objectNames[155] = "obj_Antorcha";
	global.__objectNames[156] = "obj_Pinchos";
	global.__objectNames[157] = "objSpikeBlock";
	global.__objectNames[158] = "obj_Bloqueador_Activado_Rojo";
	global.__objectNames[159] = "obj_Bloqueador_Activado_Azul";
	global.__objectNames[160] = "obj_Pinchos_Suelo";
	global.__objectNames[161] = "obj_Bloqueador_Laser";
	global.__objectNames[162] = "objSkullFlame";
	global.__objectNames[163] = "obj_Rebotador";
	global.__objectNames[164] = "obj_Atractor";
	global.__objectNames[165] = "objBuildChanger";
	global.__objectNames[166] = "objPiggyBank";
	global.__objectNames[167] = "obj_Armario";
	global.__objectNames[168] = "obj_Moneda";
	global.__objectNames[169] = "obj_Key";
	global.__objectNames[170] = "obj_BossKey";
	global.__objectNames[171] = "obj_PickupBomb";
	global.__objectNames[172] = "obj_Salud";
	global.__objectNames[173] = "obj_HalfHeart";
	global.__objectNames[174] = "obj_ShieldHeart";
	global.__objectNames[175] = "obj_TimeHeart";
	global.__objectNames[176] = "obj_SkullHeart";
	global.__objectNames[177] = "obj_GoldHeart";
	global.__objectNames[178] = "obj_BatteryHeart";
	global.__objectNames[179] = "objExperienceOrb";
	global.__objectNames[180] = "objSlimekingCrown";
	global.__objectNames[181] = "objSlimekingMoustache";
	global.__objectNames[182] = "objBosskeySpawner";
	global.__objectNames[183] = "objBomb";
	global.__objectNames[184] = "objBombExplosion";
	global.__objectNames[185] = "transicion_Jefe";
	global.__objectNames[186] = "transicion_Jugador";
	global.__objectNames[187] = "transicion_Letras";
	global.__objectNames[188] = "transicion_Control";
	global.__objectNames[189] = "control";
	global.__objectNames[190] = "floorLighting";
	global.__objectNames[191] = "obj_Light_Environment";
	global.__objectNames[192] = "obj_Light_Dynamic";
	global.__objectNames[193] = "obj_Block_Caster";
	global.__objectNames[194] = "fx_Sprite_Alpha";
	global.__objectNames[195] = "fx_Sprite";
	global.__objectNames[196] = "fx_Sprite_Persistent";
	global.__objectNames[197] = "fx_Flames";
	global.__objectNames[198] = "fx_Transition_In";
	global.__objectNames[199] = "fx_Transition_In_White";
	global.__objectNames[200] = "fx_Transition_Out";
	global.__objectNames[201] = "fx_Transition_Unlock";
	global.__objectNames[202] = "fx_Transition_Out_Full";
	global.__objectNames[203] = "objCharacterUnlock";
	global.__objectNames[204] = "fx_Transition_OutSlow";
	global.__objectNames[205] = "fx_Game_End";
	global.__objectNames[206] = "fx_Sprite_Grow";
	global.__objectNames[207] = "fx_Transition_Room";
	global.__objectNames[208] = "fxLazer";
	global.__objectNames[209] = "fxTransition2";
	global.__objectNames[210] = "fxTransition3";
	global.__objectNames[211] = "fx_Letras_Mapa";
	global.__objectNames[212] = "fxRoomFlash";
	global.__objectNames[213] = "fx_Autoguardado";
	global.__objectNames[214] = "fx_FloatingText";
	global.__objectNames[215] = "fx_Laser_Particle";
	global.__objectNames[216] = "objGuts";
	global.__objectNames[217] = "objFloorDetail";
	global.__objectNames[218] = "test_video";
	global.__objectNames[219] = "obj_Logo";
	global.__objectNames[220] = "control_Intro_ModoTorre";
	global.__objectNames[221] = "obj_Menu_Icon_ModoEndless";
	global.__objectNames[222] = "obj_Menu_Icon_ModoArcade";
	global.__objectNames[223] = "obj_Menu_Icon_Editor";
	global.__objectNames[224] = "obj_Menu_Icon_Objetos";
	global.__objectNames[225] = "obj_Menu_Icon_Salir";
	global.__objectNames[226] = "obj_Menu_Icon_Logros";
	global.__objectNames[227] = "obj_Menu_Icon_Moneda";
	global.__objectNames[228] = "obj_Menu_Icon_Ranking";
	global.__objectNames[229] = "obj_Menu_Icon_ModoTorre";
	global.__objectNames[230] = "obj_Menu_Icon_Slime";
	global.__objectNames[231] = "obj_Menu_Icon_Arcade";
	global.__objectNames[232] = "obj_Menu_Icon_Time";
	global.__objectNames[233] = "obj_Menu_Icon_Map";
	global.__objectNames[234] = "control_Primera";
	global.__objectNames[235] = "control_Menu";
	global.__objectNames[236] = "obj_Perfil";
	global.__objectNames[237] = "obj_Menu_ModoTorre";
	global.__objectNames[238] = "obj_Menu_Modos";
	global.__objectNames[239] = "obj_Menu_Ranking";
	global.__objectNames[240] = "obj_Menu_Biblioteca";
	global.__objectNames[241] = "obj_Menu_Opciones";
	global.__objectNames[242] = "obj_Menu_Volver_Menu";
	global.__objectNames[243] = "obj_Menu_Exit";
	global.__objectNames[244] = "obj_UI_Monedas";
	global.__objectNames[245] = "obj_Menu_Promo_Code";
	global.__objectNames[246] = "obj_Boton_Opciones_Ingame_Reiniciar";
	global.__objectNames[247] = "fx_Sprite_KingSlime";
	global.__objectNames[248] = "control_GameOver";
	global.__objectNames[249] = "obj_Menu_MenuPrincipal";
	global.__objectNames[250] = "obj_Menu_JugarDeNuevo";
	global.__objectNames[251] = "obj_Menu_EnviarPuntuacion";
	global.__objectNames[252] = "obj_Menu_GameOver_Play";
	global.__objectNames[253] = "obj_Nuevo_Menu_GameOver_Play";
	global.__objectNames[254] = "control_Opciones";
	global.__objectNames[255] = "obj_Menu_TipoCamara";
	global.__objectNames[256] = "obj_Menu_TipoControl";
	global.__objectNames[257] = "obj_Menu_TipoSonido";
	global.__objectNames[258] = "obj_Opciones_Volver";
	global.__objectNames[259] = "control_Ranking";
	global.__objectNames[260] = "obj_Menu_Boton_Volver";
	global.__objectNames[261] = "obj_Menu_Boton_Tiempo";
	global.__objectNames[262] = "obj_Menu_Boton_Modo";
	global.__objectNames[263] = "obj_Menu_Boton_Tower";
	global.__objectNames[264] = "obj_Menu_Boton_Dificultad";
	global.__objectNames[265] = "obj_Menu_Nuevo_Boton_Tiempo";
	global.__objectNames[266] = "obj_Menu_Nuevo_Boton_Dificultad";
	global.__objectNames[267] = "obj_Menu_Nuevo_Modo";
	global.__objectNames[268] = "obj_Menu_Nuevo_Boton_Tower";
	global.__objectNames[269] = "control_Biblioteca";
	global.__objectNames[270] = "obj_Biblioteca_Item";
	global.__objectNames[271] = "obj_Biblioteca_Comprar";
	global.__objectNames[272] = "obj_Biblioteca_Desbloqueados";
	global.__objectNames[273] = "obj_Biblioteca_Pagina";
	global.__objectNames[274] = "obj_Biblioteca_Pagina_Icon";
	global.__objectNames[275] = "obj_Biblioteca_Nuevo_Pagina";
	global.__objectNames[276] = "obj_Biblioteca_Nuevo_Buy";
	global.__objectNames[277] = "obj_Menu_ModoTorre_Play";
	global.__objectNames[278] = "obj_Menu_Modo_Endless";
	global.__objectNames[279] = "obj_Menu_Modo_Arcade";
	global.__objectNames[280] = "obj_Menu_Continuar";
	global.__objectNames[281] = "obj_Menu_Continuar_Endless";
	global.__objectNames[282] = "obj_Menu_Continuar_Arcade";
	global.__objectNames[283] = "obj_Menu_Modo_Dificultad";
	global.__objectNames[284] = "obj_Menu_Nuevo_Controller";
	global.__objectNames[285] = "parent_Menu_Nuevo";
	global.__objectNames[286] = "obj_Menu_Nuevo_Logo";
	global.__objectNames[287] = "obj_Menu_Nuevo_Stats";
	global.__objectNames[288] = "obj_Menu_Nuevo_Black";
	global.__objectNames[289] = "obj_Menu_Nuevo_Play";
	global.__objectNames[290] = "obj_Menu_Nuevo_Challenges";
	global.__objectNames[291] = "obj_Menu_Nuevo_Ranking";
	global.__objectNames[292] = "obj_Menu_Nuevo_Opciones";
	global.__objectNames[293] = "obj_Menu_Nuevo_Items";
	global.__objectNames[294] = "obj_Menu_Nuevo_Pets";
	global.__objectNames[295] = "obj_Menu_Nuevo_Exit";
	global.__objectNames[296] = "obj_Menu_Nuevo_Back";
	global.__objectNames[297] = "obj_Menu_Nuevo_CharacterSelect";
	global.__objectNames[298] = "obj_Menu_Nuevo_Codigo";
	global.__objectNames[299] = "obj_Menu_Nuevo_Adventure_Mode";
	global.__objectNames[300] = "obj_Menu_Nuevo_Endless_Mode";
	global.__objectNames[301] = "obj_Menu_Nuevo_Endless_Mode_Play";
	global.__objectNames[302] = "obj_Menu_Nuevo_DailyRun_Mode";
	global.__objectNames[303] = "obj_Menu_Nuevo_DailyRun_Mode_Play";
	global.__objectNames[304] = "obj_Menu_Nuevo_Endless_Info";
	global.__objectNames[305] = "obj_Menu_Nuevo_DailyRun_Info";
	global.__objectNames[306] = "obj_Menu_Nuevo_Arcade_Mode";
	global.__objectNames[307] = "obj_Menu_Nuevo_Audio";
	global.__objectNames[308] = "obj_Menu_Nuevo_Autosave";
	global.__objectNames[309] = "obj_Menu_Nuevo_Continuar";
	global.__objectNames[310] = "obj_Menu_Nuevo_Quality";
	global.__objectNames[311] = "obj_Menu_Nuevo_Dificultad";
	global.__objectNames[312] = "obj_Menu_Nuevo_Seed";
	global.__objectNames[313] = "obj_Menu_Nuevo_Freebies";
	global.__objectNames[314] = "obj_Menu_Nuevo_ControllerMap";
	global.__objectNames[315] = "obj_Menu_Nuevo_DefaultControllerMap";
	global.__objectNames[316] = "obj_Menu_Nuevo_Fake_Objetivo";
	global.__objectNames[317] = "control_Pets";
	global.__objectNames[318] = "obj_Pets_Comprar";
	global.__objectNames[319] = "selectionController";
	global.__objectNames[320] = "objCharacterInfo";
	global.__objectNames[321] = "objCharacterSelect";
	global.__objectNames[322] = "objCharacterSelectPrevious";
	global.__objectNames[323] = "objCharacterSelectNext";
	global.__objectNames[324] = "challengeSelectionController";
	global.__objectNames[325] = "objChallengeInfo";
	global.__objectNames[326] = "objChallengeSelect";
	global.__objectNames[327] = "obj_UI_Map";
	global.__objectNames[328] = "objCutsceneGeneral";
	global.__objectNames[329] = "objCutsceneIntro";
	global.__objectNames[330] = "objCutsceneTransition";
	global.__objectNames[331] = "objCutscene01Controller";
	global.__objectNames[332] = "sprCutscene01Muzzy";
	global.__objectNames[333] = "objCutscene01House";
	global.__objectNames[334] = "objCutscene01Moon";
	global.__objectNames[335] = "objCutscene01Mountains";
	global.__objectNames[336] = "objCutscene01Night";
	global.__objectNames[337] = "objCutscene01Background";
	global.__objectNames[338] = "objCutscene01Slimeking";
	global.__objectNames[339] = "objCutscene01SlimekingLaugh";
	global.__objectNames[340] = "objCutscene01SmokeSpawner";
	global.__objectNames[341] = "objCutscene01Tower";
	global.__objectNames[342] = "objCutscene01Player";
	global.__objectNames[343] = "objCutscene01Woods";
	global.__objectNames[344] = "objCutscene01Smoke";
	global.__objectNames[345] = "objCutscene01SmallRock";
	global.__objectNames[346] = "objCutscene01MountainsF";
	global.__objectNames[347] = "objCutscene01Slimeking2";
	global.__objectNames[348] = "objCutscene01Hair";
	global.__objectNames[349] = "objCutscene01Foreground";
	global.__objectNames[350] = "objCutscene01Dust";
	global.__objectNames[351] = "objCutscene02Controller";
	global.__objectNames[352] = "objCutscene02Overlay";
	global.__objectNames[353] = "objCutscene02SlimekingBig";
	global.__objectNames[354] = "objCutscene02Particles";
	global.__objectNames[355] = "objCutscene03Controller";
	global.__objectNames[356] = "objCutscene03Background";
	global.__objectNames[357] = "objCutscene03Bar";
	global.__objectNames[358] = "objCutscene03Bartender";
	global.__objectNames[359] = "objCutscene03Door";
	global.__objectNames[360] = "objCutscene03Flash";
	global.__objectNames[361] = "objCutscene03Table";
	global.__objectNames[362] = "objCutscene03People";
	global.__objectNames[363] = "objCutscene03Slimeking";
	global.__objectNames[364] = "objCutscene03SlimekingMoustache";
	global.__objectNames[365] = "objCutscene03WindowGlow";
	global.__objectNames[366] = "objCutscene03Overlay";
	global.__objectNames[367] = "objCutscene03Cry";
	global.__objectNames[368] = "objCutscene04Character";
	global.__objectNames[369] = "objCutscene04Background";
	global.__objectNames[370] = "objCutscene04LightCircle";
	global.__objectNames[371] = "objCutscene04Dust";
	global.__objectNames[372] = "objCutscene04FireParticleSpawner";
	global.__objectNames[373] = "objCutscene04FireParticle";
	global.__objectNames[374] = "objCutscene04Controller";
	global.__objectNames[375] = "objCutscene05Controller";
	global.__objectNames[376] = "objCutscene05BG";
	global.__objectNames[377] = "objCutscene05Player";
	global.__objectNames[378] = "objCutscene05Crown";
	global.__objectNames[379] = "objCutscene05Slimeking";
	global.__objectNames[380] = "objCutscene05Stairs";
	global.__objectNames[381] = "objCutscene06Controller";
	global.__objectNames[382] = "objCutscene06BG";
	global.__objectNames[383] = "objCutscene06Portal";
	global.__objectNames[384] = "objCutscene07Controller";
	global.__objectNames[385] = "objCutscene07BG";
	global.__objectNames[386] = "objCutscene07Throne";
	global.__objectNames[387] = "objCutscene07Player";
	global.__objectNames[388] = "objCutscene07Congratulations";
	global.__objectNames[389] = "objItemInfo";
	global.__objectNames[390] = "control_GamepadMapping";
	global.__objectNames[391] = "control_Steam";
	global.__objectNames[392] = "gamepad_MenuNav";


	// create another array that has the correct entries
	var len = array_length_1d(global.__objectDepths);
	global.__objectID2Depth = [];
	for( var i=0; i<len; ++i ) {
		var objID = asset_get_index( global.__objectNames[i] );
		if (objID >= 0) {
			global.__objectID2Depth[ objID ] = global.__objectDepths[i];
		} // end if
	} // end for


}
